### ISSUE TITLE
A11y Checklist: Mobile and Touch Accessibility

### ISSUE THREAD

**Issue by g-omarsdottir** [JohnnySonTrinh/all-inclusive#32]
Connected to Epic #31 

Mobile and Touch Accessibility: Optimize for All Devices
•	Orientation Flexibility: Ensure your site can rotate to any orientation without issues.
Link: https://www.w3.org/WAI/WCAG22/Understanding/orientation.html
•	No Horizontal Scrolling: Eliminate horizontal scrolling for a smoother user experience.
Link: https://www.w3.org/WAI/WCAG22/Understanding/reflow.html 
•	Easy Activation: Make sure buttons and icons are easily tappable for all hand sizes and ability.
Link: https://www.w3.org/WAI/WCAG22/Understanding/target-size-enhanced.html 
•	Sufficient Spacing: Provide ample space between interactive items to aid navigation. (Nota bene: the smallest x on advertisements)
Link: https://www.w3.org/WAI/WCAG22/Understanding/bypass-blocks.html 
Remember: A mobile-friendly design enhances accessibility and usability for everyone!

**Comment by D0bledore** [comment]
DONE
