### ISSUE TITLE
A11y Checklist: Animation Accessibility

### ISSUE THREAD

**Issue by g-omarsdottir** [JohnnySonTrinh/all-inclusive#33]
Connected to Epic #31 

Animation Accessibility: Keep It Subtle and Safe
•	Limit Flashing: Ensure animations are subtle to avoid triggering seizures or distracting users with cognitive disabilities.
https://www.w3.org/WAI/WCAG22/Understanding/three-flashes-or-below-threshold.html 
•	Respect Motion Preferences: Use the prefers-reduced-motion media query to disable or slow down animations for users who need it.
https://www.w3.org/WAI/WCAG22/Understanding/animation-from-interactions.html 
Remember: Thoughtful animation design enhances user experience while prioritizing safety and accessibility!

**Comment by D0bledore** [comment]
ITS ON THE PAGE
