### ISSUE TITLE
A11y Checklist: Appearance

### ISSUE THREAD

**Issue by g-omarsdottir** [JohnnySonTrinh/all-inclusive#34]
Epic #31 

Appearance: Ensure Accessibility in Design
•	Specialized Browsing Modes: Test your content in modes like High Contrast or Inverted Colors to ensure legibility and clarity.
https://www.w3.org/WAI/WCAG22/Understanding/use-of-color.html 
•	Text Size: Increase text size to 200% and check for readability and overlap.
https://www.w3.org/WAI/WCAG22/Understanding/resize-text.html 
•	Content Proximity: Ensure good spacing between elements for easy navigation.
https://www.w3.org/WAI/WCAG22/Understanding/sensory-characteristics.html 
•	Color Use: Confirm that information isn't conveyed by color alone; check visibility in grayscale.
https://www.w3.org/WAI/WCAG22/Understanding/use-of-color.html 
•	Instructions: Provide cues using a mix of visual and audio characteristics, avoiding reliance on one method.
https://www.w3.org/WAI/WCAG22/Understanding/sensory-characteristics.html 
•	Consistent Layout: Maintain a simple, straightforward layout to enhance usability.
https://www.w3.org/WAI/WCAG22/Understanding/reflow.html 
Remember: A well-designed appearance improves accessibility for all users!

**Comment by D0bledore** [comment]
Super done
