### ISSUE TITLE
A11y Checklist: Resize text

### ISSUE THREAD

**Issue by g-omarsdottir** [JohnnySonTrinh/all-inclusive#35]
Epic #31 

Resize text
•	Increase to 200%: Test if all content remains readable.
•	Check for Overlap: Ensure no text or elements overlap when resized.
•	Maintain Clarity: Verify that all information is still accessible and distinguishable.
Remember: Accessible text size enhances readability for everyone!
Link: https://www.w3.org/WAI/WCAG22/Understanding/resize-text.html

**Comment by D0bledore** [comment]
Done!
