### ISSUE TITLE
A11y Checklist: Audio

### ISSUE THREAD

**Issue by g-omarsdottir** [JohnnySonTrinh/all-inclusive#37]
Epic #31 

Audio Accessibility: Make Sound Understandable
Key check for audio content:
•	Confirm Transcripts: Ensure all audio has corresponding transcripts for those who are deaf or hard of hearing, allowing users to engage with the content at their own pace.
Remember: Providing transcripts enhances accessibility and ensures that everyone can access your audio content effectively.
Link: https://www.w3.org/WAI/WCAG22/Understanding/non-text-content.html

**Comment by D0bledore** [comment]
Yes Maam
