### ISSUE TITLE
A11y Check: Video Accessibility

### ISSUE THREAD

**Issue by g-omarsdottir** [JohnnySonTrinh/all-inclusive#38]
Epic #31 

Video Accessibility: Ensure Everyone Can Watch
Key checks for video content:
•	Confirm Captions: Ensure all videos have captions for those who are deaf or hard of hearing.
•	Eliminate Seizure Triggers: Remove any strobing or flashing animations to prevent seizure risks.
Remember: Accessible videos empower all users to engage with your content safely and effectively.

Link: https://www.w3.org/WAI/WCAG22/Understanding/captions-prerecorded.html, https://www.w3.org/WAI/WCAG22/Understanding/three-flashes-or-below-threshold.html

**Comment by D0bledore** [comment]
Its on a card
