### ISSUE TITLE
A11y Checklist: Media Control

### ISSUE THREAD

**Issue by g-omarsdottir** [JohnnySonTrinh/all-inclusive#39]
#31 

Media Control: Keep It User-Friendly
No autoplay, please!
Key points:
•	Avoid autoplaying audio and video to prevent distractions and triggers for disabilities.
•	Ensure media controls are accessible with proper markup (e.g., mute buttons, volume sliders).
•	Provide a global pause function, allowing users to pause media easily using the Space key without disrupting page scrolling.
Remember: Thoughtful media control enhances accessibility and creates a more pleasant user experience for everyone.

Links: https://www.w3.org/WAI/WCAG22/Understanding/audio-control.html , https://www.w3.org/WAI/WCAG22/Understanding/info-and-relationships.html , https://www.w3.org/WAI/WCAG22/Understanding/keyboard.html

**Comment by D0bledore** [comment]
Done!
