### ISSUE TITLE
A11y Checklist: Error Messaging

### ISSUE THREAD

**Issue by g-omarsdottir** [JohnnySonTrinh/all-inclusive#40]
#31 

Error Messaging: Clear Guidance for Users
Connect errors to inputs for clarity
Key practices:
•	Associate error messages with the corresponding input using aria-describedby
•	Use aria-invalid="true" to indicate an error state
•	Ensure error messages are visible and informative
Remember: Clear error identification helps all users, especially those with assistive technologies, understand and correct their mistakes effortlessly.
Link: https://www.w3.org/WAI/WCAG22/Understanding/error-identification.html

**Comment by D0bledore** [comment]
Done!
