### ISSUE TITLE
A11y Checklist: inputs autocomplete

### ISSUE THREAD

**Issue by g-omarsdottir** [JohnnySonTrinh/all-inclusive#41]
#31 

Inputs: use autocomplete where appropriate.
[1.3.5 Identify Input Purpose](https://www.w3.org/WAI/WCAG22/Understanding/identify-input-purpose.html)
[Providing a mechanism](https://www.w3.org/TR/html52/sec-forms.html#sec-autofill) to help people more quickly, easily, and accurately fill in form fields that ask for common information (for example, name, address, phone number).

Autocomplete: Speed Up Form Filling
Make data entry a breeze!Key benefits:
•	Use the autocomplete attribute for common fields like name, address, and phone number
•	Help users fill out forms quickly and accurately
•	Enhance accessibility for all, especially those with disabilities
Remember: Autocomplete isn't just convenient—it's a powerful tool for improving user experience and ensuring everyone can navigate your forms with ease.
Link: https://www.w3.org/WAI/WCAG22/Understanding/identify-input-purpose.html

**Comment by D0bledore** [comment]
Done
