### ISSUE TITLE
A11y Checklist: Form Grouping

### ISSUE THREAD

**Issue by g-omarsdottir** [JohnnySonTrinh/all-inclusive#42]
#31 

Form Grouping: Organize with Purpose

Fieldsets and Legends: Your Form's Best FriendsKey benefits:
•	Group related inputs logically
•	Enhance screen reader navigation
•	Improve form comprehension
Best practices:
•	Use <fieldset> to group related inputs
•	Add <legend> to describe each group
•	Keep legends concise and informative
Remember: Well-structured forms guide users smoothly through data entry, improving accessibility and user experience for everyone.

Link: https://www.w3.org/WAI/WCAG22/Understanding/info-and-relationships.html

**Comment by D0bledore** [comment]
Also done
