### ISSUE TITLE
A11y Checklist: Forms input

### ISSUE THREAD

**Issue by g-omarsdottir** [JohnnySonTrinh/all-inclusive#43]
#31 

Forms: Your Gateway to User Interaction
Make every input count
Key principles:
•	Pair each input with a label
•	Use for and id attributes to connect them
•	Ensure clear, descriptive labels
Best practices:
•	Enhance accessibility for all users
•	Improve form usability and understanding
•	Support various assistive technologies
Remember: A well-labeled form is like a friendly conversation, guiding users effortlessly through their tasks.
Link: https://www.w3.org/WAI/WCAG22/Understanding/on-input.html

**Comment by D0bledore** [comment]
Done
