### ISSUE TITLE
A11y Checklist: Tables and Tabular Data

### ISSUE THREAD

**Issue by g-omarsdottir** [JohnnySonTrinh/all-inclusive#44]
#31 

Tables: Organize Data with Precision
Tabular Data, Perfectly Presented
When to use tables:
•	Display data in rows and columns
•	Present structured, multi-dimensional information
•	Enhance readability and comprehension
Best practices:
•	Use semantic HTML <table> element
•	Include <th> for headers
•	Ensure screen reader compatibility
https://www.w3.org/WAI/WCAG22/Understanding/info-and-relationships.html
•	Use <th> with appropriate scope attributes for table headers to enhance structure and accessibility for assistive technologies. https://www.w3.org/WAI/WCAG22/Understanding/parsing.html
•	Use the <caption> element to provide a concise title for your table, clearly describing its content for all users. https://www.w3.org/WAI/WCAG22/Understanding/headings-and-labels.html 
Remember: Tables are your data's best friend, making complex information crystal clear for all users.

**Comment by D0bledore** [comment]
On a card in the core concepts page
