### ISSUE TITLE
A11y Checklist: Focus States and keyboard navigation

### ISSUE THREAD

**Issue by g-omarsdottir** [JohnnySonTrinh/all-inclusive#46]
#31 

Focus States: Your Digital Navigation Beacon
Make Every Interaction Crystal Clear
Why focus states matter:
•	Visual Roadmap: Show exactly where keyboard users are
•	Equal Access: Give keyboard users the same clarity mouse users enjoy
•	WCAG Requirement: Mandatory for web accessibility
Key principles:
•	Ensure high contrast
•	Design consistent indicators
•	Make focus states obvious across all interactive elements
Remember: A focus state is like a digital spotlight, guiding users precisely where they are on the page.
Link: https://www.w3.org/WAI/WCAG22/Understanding/focus-visible.html

**Comment by D0bledore** [comment]
On a card in the core concepts page
