### ISSUE TITLE
A11y Checklist: Focus Visibility

### ISSUE THREAD

**Issue by g-omarsdottir** [JohnnySonTrinh/all-inclusive#54]
#31 

Focus Visibility: Your Navigation Beacon
Make keyboard navigation crystal clear
Key principles:
•	Ensure every interactive element has a distinct focus state
•	Use clear, high-contrast indicators
•	Help users track their location instantly
Remember: A visible focus style is your user's GPS through the digital landscape.
Link: https://www.w3.org/WAI/WCAG22/Understanding/focus-visible.html

**Comment by D0bledore** [comment]
On a card in the core concepts page
