### ISSUE TITLE
A11y Checklist: Focus Control - Empower, don't overpower

### ISSUE THREAD

**Issue by g-omarsdottir** [JohnnySonTrinh/all-inclusive#55]
Focus Control: Respect User Navigation
Empower, don't overpower
Key focus considerations:
•	Avoid unexpected focus shifts
•	Use autofocus sparingly, if at all
•	Consider diverse user needs
Remember: Respecting user control enhances accessibility and improves overall user experience for everyone.
Link: https://www.w3.org/WAI/WCAG22/Understanding/focus-order.html

**Comment by D0bledore** [comment]
On a card in the core concepts page
