### ISSUE TITLE
A11y Checklist: Linear Flow

### ISSUE THREAD

**Issue by g-omarsdottir** [JohnnySonTrinh/all-inclusive#56]
#31 

Linear Flow: The Key to Seamless Navigation
Keep it natural, keep it simple
Optimize your content flow:
•	Remove unnecessary tabindex values
•	Let focusable elements shine naturally
•	Reserve tabindex="0" and "-1" for special cases
Remember: A logical structure is the foundation of effortless navigation for all users
Link: https://www.w3.org/WAI/WCAG22/Understanding/focus-order.html

**Comment by D0bledore** [comment]
On a card in the core concepts page
