### ISSUE TITLE
A11y Checklist: Page Titles

### ISSUE THREAD

**Issue by g-omarsdottir** [JohnnySonTrinh/all-inclusive#58]
#31 

Page Titles: Your Website's First Impression
Make it unique, make it count!
A distinctive title for each page:
•	Guides users instantly
•	Boosts accessibility 
•	Enhances navigation with many open tabs
Remember: It's often the first thing screen readers announce
Link: https://www.a11yproject.com/checklist/#provide-a-unique-title-for-each-page-or-view

**Comment by D0bledore** [comment]
On a card in the core concepts page
