### ISSUE TITLE
A11y Checklist: global code basics

### ISSUE THREAD

**Issue by g-omarsdottir** [JohnnySonTrinh/all-inclusive#59]
#31 

HTML Validation and Language Attributes

- Validate Your HTML: Ensuring valid HTML provides a consistent experience across browsers and assists assistive technologies.
Link to Validator: https://validator.w3.org/nu/
- Use lang Attribute: Always include a lang attribute in the <html> element to help screen readers pronounce content correctly.
https://www.w3.org/WAI/WCAG22/Understanding/language-of-page.html 
By following these practices, you enhance accessibility and improve user experience on your website.

**Comment by D0bledore** [comment]
On a card in the core concepts page
